
tasks:
  - init: npm install && npm run compile



vscode:
  extensions:
    - gengjiawen.vscode-npm-dependencygitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
    - redhat.fabric8-analytics# and commit this file to your remote git repository to share the goodness with others.
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
tasks:
  - init: npm install && npm run compile

